version: '3.8'

services:
  cloudflared:
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    deploy:
      replicas: 2
    image: cloudflare/cloudflared:latest
    restart: always
  redis:
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: redis:latest
    restart: always
  postgres:
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  staffportal:
    deploy:
      replicas: 2
    image: ghcr.io/42-bangkok/staffportal:latest
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  postgres_data:
